# Generated by Django 5.1.7 on 2025-03-27 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Agenda Categories',
            },
        ),
        migrations.CreateModel(
            name='MemoirsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Memoirs Categories',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('studies', models.CharField(max_length=500)),
                ('profession', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('footnote', models.TextField()),
                ('file_path', models.TextField(help_text='Absolute path to the file on the storage')),
                ('status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft'), ('withdrawn', 'Withdrawn')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.agendacategories')),
            ],
        ),
        migrations.CreateModel(
            name='Memoirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('author_email', models.EmailField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('resume', models.TextField()),
                ('content', models.TextField()),
                ('file_path', models.TextField(help_text='Absolute path to the file on the storage')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Reading time in minutes')),
                ('visualizations', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft'), ('withdrawn', 'Withdrawn')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memoir_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.memoirscategories')),
            ],
        ),
        migrations.CreateModel(
            name='MemoirsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=2000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memoir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='frontend.memoirs')),
            ],
        ),
    ]
