# Generated by Django 5.2 on 2025-04-23 06:09

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Agenda Categories',
            },
        ),
        migrations.CreateModel(
            name='MemoirsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Memoirs Categories',
            },
        ),
        migrations.CreateModel(
            name='SurveyRespondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=500)),
                ('name', models.EmailField(max_length=200)),
                ('last_name', models.EmailField(max_length=200)),
                ('national_id', models.CharField(max_length=20)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('country', models.CharField(default='Colombia')),
                ('department', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('geolocalization', models.CharField(help_text='DIVIPOLA DANE', max_length=150)),
                ('geolocalization_coordinate', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Respondents',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('studies', models.CharField(max_length=500)),
                ('profession', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('footnote', models.TextField()),
                ('file_path', models.TextField(help_text='Absolute path to the file on the storage')),
                ('status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft'), ('withdrawn', 'Withdrawn')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='backend.agendacategories')),
            ],
            options={
                'verbose_name_plural': 'Agenda',
            },
        ),
        migrations.CreateModel(
            name='Memoirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('author_email', models.EmailField(max_length=200)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('resume', models.TextField()),
                ('content', models.TextField()),
                ('file_path', models.TextField(blank=True, help_text='Absolute path to the file on the storage')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Reading time in minutes')),
                ('visualizations', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft'), ('withdrawn', 'Withdrawn')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoirs', to='backend.memoirscategories')),
            ],
            options={
                'verbose_name_plural': 'Memoirs',
            },
        ),
        migrations.CreateModel(
            name='MemoirsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=2000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memoir', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.memoirs')),
            ],
            options={
                'verbose_name_plural': 'Memoirs Comments',
            },
        ),
        migrations.CreateModel(
            name='EncryptedUserSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('survey_respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.surveyrespondent')),
            ],
        ),
    ]
