# Generated by Django 5.1.7 on 2025-04-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoirscomments',
            options={'verbose_name_plural': 'Memoirs Comments'},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='memoirs',
            name='memoir_category_id',
        ),
        migrations.RemoveField(
            model_name='memoirscomments',
            name='memoir_id',
        ),
        migrations.AddField(
            model_name='agenda',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='backend.agendacategories'),
        ),
        migrations.AddField(
            model_name='memoirs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memoirs', to='backend.memoirscategories'),
        ),
        migrations.AddField(
            model_name='memoirscomments',
            name='memoir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.memoirs'),
        ),
        migrations.AlterField(
            model_name='memoirs',
            name='author_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memoirs',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
