# Generated by Django 5.1.7 on 2025-04-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_memoirscomments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoirs',
            name='file_path',
            field=models.TextField(blank=True, help_text='Absolute path to the file on the storage'),
        ),
    ]
