# Generated by Django 5.1.7 on 2025-04-03 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_memoirs_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoirs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoirs', to='backend.memoirscategories'),
        ),
    ]
